TheAgentCompany/TheAgentCompany

evaluation/summarise_results.py
=> [Evaluation] Add cost estimate for gemini-2.0-flash-exp

.github/publish-images.sh, .github/publish_task_images.sh, .github/workflows/task-release.yml
=> Add CI to publish all task images

.github/publish_task_images.sh
=> [CI] Convert ghcr image name from upper case to lower case

evaluation/run_eval.py, evaluation/run_eval.sh
=> [Evaluation] Use released images for experiments

.github/workflows/benchmark-runner.yml
and hide it to make it harder for malicious DDOS attacks.
---
=> Make on-demand evaluation configurable

.github/workflows/benchmark-runner.yml
=> [CI] Rename benchmark runner concurrency group

evaluation/run_eval.sh
=> [Evaluation] Fix task image removal after evaluation

evaluation/summarise_results.py
=> Summarize results based on job nature category

evaluation/summarise_results.py
Example:
```
| Average Score for gitlab | 0.40
| Perfect Completions for gitlab | 22/71 (30.99%) |
| Average Score for plane | 0.50
| Perfect Completions for plane | 7/17 (41.18%) |
| Average Score for owncloud | 0.22
| Perfect Completions for owncloud | 7/70 (10.00%) |
| Average Score for rocketchat | 0.35
| Perfect Completions for rocketchat | 17/79 (21.52%) |
```
=> Summarize task score based on service category

evaluation/summarise_results.py
=> Use percentage in categorised score reporting

evaluation/summarise_results.py
=> Add pm category into evaluation analysis script

README.md
=> README.md: Fix dead link, and reword contribution section

LICENSE, poetry.lock, pyproject.toml, servers/README.md
1. Change "neulab" to "TheAgentCompany" in doc, license, and project definition
2. Remove unused dependencies, and name the group to clarify a bit
=> Clean up project definition and dependencies

evaluation/summarise_results.py
1. I mistakenly used pro's price to compute flash model's cost
2. I didn't compute longer context (> 128k)'s cost properly for gemini
=> Fix gemini models' evaluation cost computation formula

README.md
=> Doc: refactor readme

README.md
=> Doc: add cite

README.md, docs/EVALUATION.md, servers/README.md
=> [doc] Complete step-by-step guide to run evaluation

README.md, docs/EVALUATION.md
=> [doc] Format README.md and fix dead links

docs/SETUP.md, servers/README.md
=> [doc] Server setup doc polish

README.md
=> README.md: Update task folder structure

workspaces/README.md
It would be handy to have the full list of 175 task images' names somewhere.
---
=> [doc] Add link to download the list of 175 task images

docs/SETUP.md
Host networking must be enabled to run servers on Macbook.
=> SETUP.md: Explain Macbook's host setting

README.md, docs/SETUP.md, servers/README.md, servers/setup.bat
=> Add script and doc for windows setup

docs/SETUP.md
=> docs: update SETUP.md

docs/EVALUATION.md
Some people might get confused by "how to do browsing in a container"? This PR adds a bit more explanation.
---
=> EVALUATION.md: Explain more on browsing

servers/api-server/utils.py
Fix a missing import bug in error code path. This issue doesn't affect the normal code path.
Fixes #1006 
---
=> api-server: Fix a missing import in error code path

README.md
How exactly should one prompt their agent for this benchmark? It is more verbosely explained in https://github.com/TheAgentCompany/TheAgentCompany/blob/main/docs/EVALUATION.md doc, but not super clear in the root README file.
This PR explains the baseline choice and points out an alternative.
---
=> README.md: Explain how to prompt the task description

evaluation/browsing.py, evaluation/run_eval.py
=> [Eval harness] Update to accomodate to latest OpenHands

evaluation/browsing.py
=> [Eval harness] Fix browsing.py API change of OpenHands

workspaces/tasks/sde-update-readme/task.md
=> fix readme

workspaces/tasks/hr-check-attendance-multiple-days-department-with-chat/task.md, workspaces/tasks/hr-check-attendance-multiple-days-department/checkpoints.md, workspaces/tasks/hr-check-attendance-multiple-days-department/task.md, workspaces/tasks/sde-report-agent-repos/scenarios.json
=> Fix prompt

README.md
When you run the container, I think you need to run with `--network host`, otherwise the container can't connect to `the-agent-company.com `
---
=> Update Docs for starting own container

docs/SETUP.md
=> Doc: add more details for api-server container downloading problem

README.md
=> README.md: Add Amazon EC2 reference

evaluation/summarise_results.py
=> Fix gemini price computation for gemini 2.0 flash

workspaces/tasks/sde-debug-crashed-server/evaluator.py
This PR adds timeout of **20 seconds** for **connection establishment** and up to **5 minutes** for the server to send a **response**.
=> #1038: request timeout

evaluation/README.md, evaluation/build_oh_runtime_images.sh, evaluation/run_eval.sh
=> [Evaluation] Add a mode that only runs tasks with NPC (LLM-as-Colleagues) 
